unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g mode-keys vi

# Windows
bind c new-window
bind n next-window
bind p previous-window
bind w list-windows
bind , command-prompt "rename-window '%%'"
bind & kill-window

# Panes
bind - split-window -v
bind | split-window -h
bind Left select-pane -L
bind Right select-pane -R
bind Up select-pane -U
bind Down select-pane -D
bind o swap-pane -D
bind x kill-pane
bind Space next-layout

# Copy mode (vi)
bind [ copy-mode
bind ] paste-buffer
bind -T copy-mode-vi Space send-keys -X begin-selection
bind -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -sel clip -i'

# Other
bind S set-window-option synchronize-panes
bind / copy-mode \; send-keys "/"
bind r source-file ~/.tmux.conf \; display "Config reloaded!"
bind ? list-keys